services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: loan-management-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "verYs3cret"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "verYs3cret", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  init-db:
    build:
      context: .
      dockerfile: Dockerfile.init-db
    container_name: loan-management-init-db
    environment:
      SA_PASSWORD: "verYs3cret" # Debe coincidir con SA_PASSWORD de 'db'
    depends_on:
      db:
        condition: service_healthy


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-management-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=LoanManagementDB;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "verYs3cret"
    depends_on:
      init-db:
        condition: service_completed_successfully

volumes:
  sqlserver_data:
