services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=Developer'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
      - 'MSSQL_DATABASE=loanmanagement'
    ports:
      - '1433:1433'
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    restart: always